//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace banks_dictonary.CreditInfoWS {
	using System;
	using System.Web.Services;
	using System.Diagnostics;
	using System.Web.Services.Protocols;
	using System.Xml.Serialization;
	using System.ComponentModel;
	using System.Data;
	
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "5.1.0.5216-0e58df71")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name="CreditOrgInfoSoap", Namespace="http://web.cbr.ru/")]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
	public partial class CreditOrgInfo : System.Web.Services.Protocols.SoapHttpClientProtocol {
		
		/// <remarks/>
		public CreditOrgInfo() {
			this.Url = "http://www.cbr.ru/CreditInfoWebServ/CreditOrgInfo.asmx";
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/EnumBIC_XML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Xml.XmlNode EnumBIC_XML() {
			object[] results = this.Invoke("EnumBIC_XML", new object[0]);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginEnumBIC_XML(System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("EnumBIC_XML", new object[0], callback, asyncState);
		}
		
		/// <remarks/>
		public System.Xml.XmlNode EndEnumBIC_XML(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/GetFormsMaxDate", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.DateTime GetFormsMaxDate(int code) {
			object[] results = this.Invoke("GetFormsMaxDate", new object[] {
						code});
			return ((System.DateTime)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginGetFormsMaxDate(int code, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("GetFormsMaxDate", new object[] {
						code}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.DateTime EndGetFormsMaxDate(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.DateTime)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/LastUpdate", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.DateTime LastUpdate() {
			object[] results = this.Invoke("LastUpdate", new object[0]);
			return ((System.DateTime)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginLastUpdate(System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("LastUpdate", new object[0], callback, asyncState);
		}
		
		/// <remarks/>
		public System.DateTime EndLastUpdate(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.DateTime)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/EnumBIC", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet EnumBIC() {
			object[] results = this.Invoke("EnumBIC", new object[0]);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginEnumBIC(System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("EnumBIC", new object[0], callback, asyncState);
		}
		
		/// <remarks/>
		public System.Data.DataSet EndEnumBIC(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Data101FormExXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Xml.XmlNode Data101FormExXML(object[] CredorgNumbers, int IndID, System.DateTime DateFrom, System.DateTime DateTo) {
			object[] results = this.Invoke("Data101FormExXML", new object[] {
						CredorgNumbers,
						IndID,
						DateFrom,
						DateTo});
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginData101FormExXML(object[] CredorgNumbers, int IndID, System.DateTime DateFrom, System.DateTime DateTo, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Data101FormExXML", new object[] {
						CredorgNumbers,
						IndID,
						DateFrom,
						DateTo}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Xml.XmlNode EndData101FormExXML(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Data101FormEx", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet Data101FormEx(object[] CredorgNumbers, int IndID, System.DateTime DateFrom, System.DateTime DateTo) {
			object[] results = this.Invoke("Data101FormEx", new object[] {
						CredorgNumbers,
						IndID,
						DateFrom,
						DateTo});
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginData101FormEx(object[] CredorgNumbers, int IndID, System.DateTime DateFrom, System.DateTime DateTo, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Data101FormEx", new object[] {
						CredorgNumbers,
						IndID,
						DateFrom,
						DateTo}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Data.DataSet EndData101FormEx(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Data101FormXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Xml.XmlNode Data101FormXML(int CredorgNumber, int IndID, System.DateTime DateFrom, System.DateTime DateTo) {
			object[] results = this.Invoke("Data101FormXML", new object[] {
						CredorgNumber,
						IndID,
						DateFrom,
						DateTo});
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginData101FormXML(int CredorgNumber, int IndID, System.DateTime DateFrom, System.DateTime DateTo, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Data101FormXML", new object[] {
						CredorgNumber,
						IndID,
						DateFrom,
						DateTo}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Xml.XmlNode EndData101FormXML(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Data101Form", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet Data101Form(int CredorgNumber, int IndID, System.DateTime DateFrom, System.DateTime DateTo) {
			object[] results = this.Invoke("Data101Form", new object[] {
						CredorgNumber,
						IndID,
						DateFrom,
						DateTo});
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginData101Form(int CredorgNumber, int IndID, System.DateTime DateFrom, System.DateTime DateTo, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Data101Form", new object[] {
						CredorgNumber,
						IndID,
						DateFrom,
						DateTo}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Data.DataSet EndData101Form(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Data101FullXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Xml.XmlNode Data101FullXML(int CredorgNumber, int IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
			object[] results = this.Invoke("Data101FullXML", new object[] {
						CredorgNumber,
						IndCode,
						DateFrom,
						DateTo});
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginData101FullXML(int CredorgNumber, int IndCode, System.DateTime DateFrom, System.DateTime DateTo, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Data101FullXML", new object[] {
						CredorgNumber,
						IndCode,
						DateFrom,
						DateTo}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Xml.XmlNode EndData101FullXML(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Data101FullExXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Xml.XmlNode Data101FullExXML(object[] CredorgNumbers, int IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
			object[] results = this.Invoke("Data101FullExXML", new object[] {
						CredorgNumbers,
						IndCode,
						DateFrom,
						DateTo});
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginData101FullExXML(object[] CredorgNumbers, int IndCode, System.DateTime DateFrom, System.DateTime DateTo, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Data101FullExXML", new object[] {
						CredorgNumbers,
						IndCode,
						DateFrom,
						DateTo}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Xml.XmlNode EndData101FullExXML(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Data101FullEx", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet Data101FullEx(object[] CredorgNumbers, int IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
			object[] results = this.Invoke("Data101FullEx", new object[] {
						CredorgNumbers,
						IndCode,
						DateFrom,
						DateTo});
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginData101FullEx(object[] CredorgNumbers, int IndCode, System.DateTime DateFrom, System.DateTime DateTo, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Data101FullEx", new object[] {
						CredorgNumbers,
						IndCode,
						DateFrom,
						DateTo}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Data.DataSet EndData101FullEx(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Data101FullExV2XML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Xml.XmlNode Data101FullExV2XML(object[] CredorgNumbers, string IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
			object[] results = this.Invoke("Data101FullExV2XML", new object[] {
						CredorgNumbers,
						IndCode,
						DateFrom,
						DateTo});
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginData101FullExV2XML(object[] CredorgNumbers, string IndCode, System.DateTime DateFrom, System.DateTime DateTo, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Data101FullExV2XML", new object[] {
						CredorgNumbers,
						IndCode,
						DateFrom,
						DateTo}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Xml.XmlNode EndData101FullExV2XML(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Data101FullExV2", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet Data101FullExV2(object[] CredorgNumbers, string IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
			object[] results = this.Invoke("Data101FullExV2", new object[] {
						CredorgNumbers,
						IndCode,
						DateFrom,
						DateTo});
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginData101FullExV2(object[] CredorgNumbers, string IndCode, System.DateTime DateFrom, System.DateTime DateTo, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Data101FullExV2", new object[] {
						CredorgNumbers,
						IndCode,
						DateFrom,
						DateTo}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Data.DataSet EndData101FullExV2(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Data101Full", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet Data101Full(int CredorgNumber, int IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
			object[] results = this.Invoke("Data101Full", new object[] {
						CredorgNumber,
						IndCode,
						DateFrom,
						DateTo});
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginData101Full(int CredorgNumber, int IndCode, System.DateTime DateFrom, System.DateTime DateTo, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Data101Full", new object[] {
						CredorgNumber,
						IndCode,
						DateFrom,
						DateTo}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Data.DataSet EndData101Full(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Data101FullV2XML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Xml.XmlNode Data101FullV2XML(int CredorgNumber, string IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
			object[] results = this.Invoke("Data101FullV2XML", new object[] {
						CredorgNumber,
						IndCode,
						DateFrom,
						DateTo});
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginData101FullV2XML(int CredorgNumber, string IndCode, System.DateTime DateFrom, System.DateTime DateTo, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Data101FullV2XML", new object[] {
						CredorgNumber,
						IndCode,
						DateFrom,
						DateTo}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Xml.XmlNode EndData101FullV2XML(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Data101FullV2", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet Data101FullV2(int CredorgNumber, string IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
			object[] results = this.Invoke("Data101FullV2", new object[] {
						CredorgNumber,
						IndCode,
						DateFrom,
						DateTo});
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginData101FullV2(int CredorgNumber, string IndCode, System.DateTime DateFrom, System.DateTime DateTo, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Data101FullV2", new object[] {
						CredorgNumber,
						IndCode,
						DateFrom,
						DateTo}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Data.DataSet EndData101FullV2(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Data102FormExXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Xml.XmlNode Data102FormExXML(object[] CredorgNumbers, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo) {
			object[] results = this.Invoke("Data102FormExXML", new object[] {
						CredorgNumbers,
						SymbCode,
						DateFrom,
						DateTo});
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginData102FormExXML(object[] CredorgNumbers, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Data102FormExXML", new object[] {
						CredorgNumbers,
						SymbCode,
						DateFrom,
						DateTo}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Xml.XmlNode EndData102FormExXML(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Data102FormEx", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet Data102FormEx(object[] CredorgNumbers, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo) {
			object[] results = this.Invoke("Data102FormEx", new object[] {
						CredorgNumbers,
						SymbCode,
						DateFrom,
						DateTo});
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginData102FormEx(object[] CredorgNumbers, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Data102FormEx", new object[] {
						CredorgNumbers,
						SymbCode,
						DateFrom,
						DateTo}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Data.DataSet EndData102FormEx(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Data102FormXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Xml.XmlNode Data102FormXML(int CredorgNumber, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo) {
			object[] results = this.Invoke("Data102FormXML", new object[] {
						CredorgNumber,
						SymbCode,
						DateFrom,
						DateTo});
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginData102FormXML(int CredorgNumber, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Data102FormXML", new object[] {
						CredorgNumber,
						SymbCode,
						DateFrom,
						DateTo}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Xml.XmlNode EndData102FormXML(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Data102Form", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet Data102Form(int CredorgNumber, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo) {
			object[] results = this.Invoke("Data102Form", new object[] {
						CredorgNumber,
						SymbCode,
						DateFrom,
						DateTo});
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginData102Form(int CredorgNumber, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Data102Form", new object[] {
						CredorgNumber,
						SymbCode,
						DateFrom,
						DateTo}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Data.DataSet EndData102Form(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Form102IndicatorsEnumXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Xml.XmlNode Form102IndicatorsEnumXML() {
			object[] results = this.Invoke("Form102IndicatorsEnumXML", new object[0]);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginForm102IndicatorsEnumXML(System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Form102IndicatorsEnumXML", new object[0], callback, asyncState);
		}
		
		/// <remarks/>
		public System.Xml.XmlNode EndForm102IndicatorsEnumXML(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Form102IndicatorsEnum", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet Form102IndicatorsEnum() {
			object[] results = this.Invoke("Form102IndicatorsEnum", new object[0]);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginForm102IndicatorsEnum(System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Form102IndicatorsEnum", new object[0], callback, asyncState);
		}
		
		/// <remarks/>
		public System.Data.DataSet EndForm102IndicatorsEnum(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Form101IndicatorsEnumXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Xml.XmlNode Form101IndicatorsEnumXML() {
			object[] results = this.Invoke("Form101IndicatorsEnumXML", new object[0]);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginForm101IndicatorsEnumXML(System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Form101IndicatorsEnumXML", new object[0], callback, asyncState);
		}
		
		/// <remarks/>
		public System.Xml.XmlNode EndForm101IndicatorsEnumXML(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Form101IndicatorsEnum", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet Form101IndicatorsEnum() {
			object[] results = this.Invoke("Form101IndicatorsEnum", new object[0]);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginForm101IndicatorsEnum(System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Form101IndicatorsEnum", new object[0], callback, asyncState);
		}
		
		/// <remarks/>
		public System.Data.DataSet EndForm101IndicatorsEnum(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/RegNumToIntCode", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public double RegNumToIntCode(double RegNumber) {
			object[] results = this.Invoke("RegNumToIntCode", new object[] {
						RegNumber});
			return ((double)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginRegNumToIntCode(double RegNumber, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("RegNumToIntCode", new object[] {
						RegNumber}, callback, asyncState);
		}
		
		/// <remarks/>
		public double EndRegNumToIntCode(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((double)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/IntCodeToRegNum", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public double IntCodeToRegNum(double IntNumber) {
			object[] results = this.Invoke("IntCodeToRegNum", new object[] {
						IntNumber});
			return ((double)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginIntCodeToRegNum(double IntNumber, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("IntCodeToRegNum", new object[] {
						IntNumber}, callback, asyncState);
		}
		
		/// <remarks/>
		public double EndIntCodeToRegNum(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((double)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/BicToIntCode", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public double BicToIntCode(string BicCode) {
			object[] results = this.Invoke("BicToIntCode", new object[] {
						BicCode});
			return ((double)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginBicToIntCode(string BicCode, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("BicToIntCode", new object[] {
						BicCode}, callback, asyncState);
		}
		
		/// <remarks/>
		public double EndBicToIntCode(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((double)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/BicToRegNumber", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public int BicToRegNumber(string BicCode) {
			object[] results = this.Invoke("BicToRegNumber", new object[] {
						BicCode});
			return ((int)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginBicToRegNumber(string BicCode, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("BicToRegNumber", new object[] {
						BicCode}, callback, asyncState);
		}
		
		/// <remarks/>
		public int EndBicToRegNumber(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((int)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/RegionsEnum", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet RegionsEnum() {
			object[] results = this.Invoke("RegionsEnum", new object[0]);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginRegionsEnum(System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("RegionsEnum", new object[0], callback, asyncState);
		}
		
		/// <remarks/>
		public System.Data.DataSet EndRegionsEnum(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/RegionsEnumXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Xml.XmlNode RegionsEnumXML() {
			object[] results = this.Invoke("RegionsEnumXML", new object[0]);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginRegionsEnumXML(System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("RegionsEnumXML", new object[0], callback, asyncState);
		}
		
		/// <remarks/>
		public System.Xml.XmlNode EndRegionsEnumXML(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/SearchByRegionCode", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet SearchByRegionCode(int RegCode) {
			object[] results = this.Invoke("SearchByRegionCode", new object[] {
						RegCode});
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginSearchByRegionCode(int RegCode, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("SearchByRegionCode", new object[] {
						RegCode}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Data.DataSet EndSearchByRegionCode(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/SearchByRegionCodeXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Xml.XmlNode SearchByRegionCodeXML(int RegCode) {
			object[] results = this.Invoke("SearchByRegionCodeXML", new object[] {
						RegCode});
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginSearchByRegionCodeXML(int RegCode, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("SearchByRegionCodeXML", new object[] {
						RegCode}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Xml.XmlNode EndSearchByRegionCodeXML(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/SearchByNameXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Xml.XmlNode SearchByNameXML(string NamePart) {
			object[] results = this.Invoke("SearchByNameXML", new object[] {
						NamePart});
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginSearchByNameXML(string NamePart, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("SearchByNameXML", new object[] {
						NamePart}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Xml.XmlNode EndSearchByNameXML(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/SearchByName", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet SearchByName(string NamePart) {
			object[] results = this.Invoke("SearchByName", new object[] {
						NamePart});
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginSearchByName(string NamePart, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("SearchByName", new object[] {
						NamePart}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Data.DataSet EndSearchByName(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/CreditInfoByIntCodeXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Xml.XmlNode CreditInfoByIntCodeXML(double InternalCode) {
			object[] results = this.Invoke("CreditInfoByIntCodeXML", new object[] {
						InternalCode});
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginCreditInfoByIntCodeXML(double InternalCode, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("CreditInfoByIntCodeXML", new object[] {
						InternalCode}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Xml.XmlNode EndCreditInfoByIntCodeXML(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/CreditInfoByIntCodeExXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Xml.XmlNode CreditInfoByIntCodeExXML(double[] InternalCodes) {
			object[] results = this.Invoke("CreditInfoByIntCodeExXML", new object[] {
						InternalCodes});
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginCreditInfoByIntCodeExXML(double[] InternalCodes, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("CreditInfoByIntCodeExXML", new object[] {
						InternalCodes}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Xml.XmlNode EndCreditInfoByIntCodeExXML(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/CreditInfoByIntCodeEx", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet CreditInfoByIntCodeEx(double[] InternalCodes) {
			object[] results = this.Invoke("CreditInfoByIntCodeEx", new object[] {
						InternalCodes});
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginCreditInfoByIntCodeEx(double[] InternalCodes, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("CreditInfoByIntCodeEx", new object[] {
						InternalCodes}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Data.DataSet EndCreditInfoByIntCodeEx(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/CreditInfoByIntCode", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet CreditInfoByIntCode(double InternalCode) {
			object[] results = this.Invoke("CreditInfoByIntCode", new object[] {
						InternalCode});
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginCreditInfoByIntCode(double InternalCode, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("CreditInfoByIntCode", new object[] {
						InternalCode}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Data.DataSet EndCreditInfoByIntCode(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/GetOffices", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet GetOffices(double IntCode) {
			object[] results = this.Invoke("GetOffices", new object[] {
						IntCode});
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginGetOffices(double IntCode, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("GetOffices", new object[] {
						IntCode}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Data.DataSet EndGetOffices(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/GetOfficesByRegion", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet GetOfficesByRegion(int RegCode) {
			object[] results = this.Invoke("GetOfficesByRegion", new object[] {
						RegCode});
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginGetOfficesByRegion(int RegCode, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("GetOfficesByRegion", new object[] {
						RegCode}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Data.DataSet EndGetOfficesByRegion(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/GetOfficesXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Xml.XmlNode GetOfficesXML(double IntCode) {
			object[] results = this.Invoke("GetOfficesXML", new object[] {
						IntCode});
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginGetOfficesXML(double IntCode, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("GetOfficesXML", new object[] {
						IntCode}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Xml.XmlNode EndGetOfficesXML(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/GetOfficesByRegionXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Xml.XmlNode GetOfficesByRegionXML(int RegCode) {
			object[] results = this.Invoke("GetOfficesByRegionXML", new object[] {
						RegCode});
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginGetOfficesByRegionXML(int RegCode, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("GetOfficesByRegionXML", new object[] {
						RegCode}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Xml.XmlNode EndGetOfficesByRegionXML(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Data134FormFullXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Xml.XmlNode Data134FormFullXML(int CredorgNumber, System.DateTime OnDate) {
			object[] results = this.Invoke("Data134FormFullXML", new object[] {
						CredorgNumber,
						OnDate});
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginData134FormFullXML(int CredorgNumber, System.DateTime OnDate, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Data134FormFullXML", new object[] {
						CredorgNumber,
						OnDate}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Xml.XmlNode EndData134FormFullXML(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Olap134Form", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet Olap134Form(string Code, int CredorgNumber, System.DateTime FromDate, System.DateTime ToDate) {
			object[] results = this.Invoke("Olap134Form", new object[] {
						Code,
						CredorgNumber,
						FromDate,
						ToDate});
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginOlap134Form(string Code, int CredorgNumber, System.DateTime FromDate, System.DateTime ToDate, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Olap134Form", new object[] {
						Code,
						CredorgNumber,
						FromDate,
						ToDate}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Data.DataSet EndOlap134Form(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Data135FormFull", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet Data135FormFull(int CredorgNumber, System.DateTime OnDate) {
			object[] results = this.Invoke("Data135FormFull", new object[] {
						CredorgNumber,
						OnDate});
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginData135FormFull(int CredorgNumber, System.DateTime OnDate, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Data135FormFull", new object[] {
						CredorgNumber,
						OnDate}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Data.DataSet EndData135FormFull(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Data135FormFullXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Xml.XmlNode Data135FormFullXML(int CredorgNumber, System.DateTime OnDate) {
			object[] results = this.Invoke("Data135FormFullXML", new object[] {
						CredorgNumber,
						OnDate});
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginData135FormFullXML(int CredorgNumber, System.DateTime OnDate, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Data135FormFullXML", new object[] {
						CredorgNumber,
						OnDate}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Xml.XmlNode EndData135FormFullXML(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Data123FormFull", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet Data123FormFull(int CredorgNumber, System.DateTime OnDate) {
			object[] results = this.Invoke("Data123FormFull", new object[] {
						CredorgNumber,
						OnDate});
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginData123FormFull(int CredorgNumber, System.DateTime OnDate, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Data123FormFull", new object[] {
						CredorgNumber,
						OnDate}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Data.DataSet EndData123FormFull(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Data123FormFullXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Xml.XmlNode Data123FormFullXML(int CredorgNumber, System.DateTime OnDate) {
			object[] results = this.Invoke("Data123FormFullXML", new object[] {
						CredorgNumber,
						OnDate});
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginData123FormFullXML(int CredorgNumber, System.DateTime OnDate, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Data123FormFullXML", new object[] {
						CredorgNumber,
						OnDate}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Xml.XmlNode EndData123FormFullXML(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Xml.XmlNode)(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/GetDatesForF123", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.DateTime[] GetDatesForF123(int CredprgNumber) {
			object[] results = this.Invoke("GetDatesForF123", new object[] {
						CredprgNumber});
			return ((System.DateTime[])(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginGetDatesForF123(int CredprgNumber, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("GetDatesForF123", new object[] {
						CredprgNumber}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.DateTime[] EndGetDatesForF123(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.DateTime[])(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/GetDatesForF101", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.DateTime[] GetDatesForF101(int CredprgNumber) {
			object[] results = this.Invoke("GetDatesForF101", new object[] {
						CredprgNumber});
			return ((System.DateTime[])(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginGetDatesForF101(int CredprgNumber, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("GetDatesForF101", new object[] {
						CredprgNumber}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.DateTime[] EndGetDatesForF101(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.DateTime[])(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/GetDatesForF102", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.DateTime[] GetDatesForF102(int CredprgNumber) {
			object[] results = this.Invoke("GetDatesForF102", new object[] {
						CredprgNumber});
			return ((System.DateTime[])(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginGetDatesForF102(int CredprgNumber, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("GetDatesForF102", new object[] {
						CredprgNumber}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.DateTime[] EndGetDatesForF102(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.DateTime[])(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/GetDatesForF134", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.DateTime[] GetDatesForF134(int CredprgNumber) {
			object[] results = this.Invoke("GetDatesForF134", new object[] {
						CredprgNumber});
			return ((System.DateTime[])(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginGetDatesForF134(int CredprgNumber, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("GetDatesForF134", new object[] {
						CredprgNumber}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.DateTime[] EndGetDatesForF134(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.DateTime[])(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/GetDatesForF135", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.DateTime[] GetDatesForF135(int CredprgNumber) {
			object[] results = this.Invoke("GetDatesForF135", new object[] {
						CredprgNumber});
			return ((System.DateTime[])(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginGetDatesForF135(int CredprgNumber, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("GetDatesForF135", new object[] {
						CredprgNumber}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.DateTime[] EndGetDatesForF135(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.DateTime[])(results[0]));
		}
		
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Data134FormFull", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public System.Data.DataSet Data134FormFull(int CredorgNumber, System.DateTime OnDate) {
			object[] results = this.Invoke("Data134FormFull", new object[] {
						CredorgNumber,
						OnDate});
			return ((System.Data.DataSet)(results[0]));
		}
		
		/// <remarks/>
		public System.IAsyncResult BeginData134FormFull(int CredorgNumber, System.DateTime OnDate, System.AsyncCallback callback, object asyncState) {
			return this.BeginInvoke("Data134FormFull", new object[] {
						CredorgNumber,
						OnDate}, callback, asyncState);
		}
		
		/// <remarks/>
		public System.Data.DataSet EndData134FormFull(System.IAsyncResult asyncResult) {
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Data.DataSet)(results[0]));
		}
	}
}
